# Generated by Django 5.2.6 on 2025-09-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoriler',
            options={'verbose_name': 'Kategoriler', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AddField(
            model_name='kategoriler',
            name='ustKategori',
            field=models.ForeignKey(blank=True, help_text='Eger bu kategori baska bir kategoriye bagliysa burayı doldurunuz.', null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.kategoriler'),
        ),
        migrations.AlterField(
            model_name='kategoriler',
            name='aktifMi',
            field=models.BooleanField(default=True),
        ),
    ]
