# Generated by Django 5.2.6 on 2025-09-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_alter_kategoriler_options_kategoriler_ustkategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='seo_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kategoriler',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
