# Generated by Django 5.2.6 on 2025-09-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_kategoriler_seo_description_kategoriler_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
