# Generated by Django 5.2.6 on 2025-09-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_markaşar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Markaşar',
            new_name='Markalar',
        ),
    ]
