# Generated by Django 5.2.6 on 2025-09-25 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_rename_markaşar_markalar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indirimli_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kisa_aciklama', models.TextField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_description', models.TextField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('aktifMi', models.BooleanField(default=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='urunresimleri')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.kategoriler')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.markalar')),
            ],
            options={
                'verbose_name': 'Urun',
                'verbose_name_plural': 'Urunler',
            },
        ),
    ]
