# Generated by Django 5.2.6 on 2025-09-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_urunler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiketler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('aktifMi', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
            },
        ),
        migrations.AddField(
            model_name='urunler',
            name='etiketler',
            field=models.ManyToManyField(blank=True, to='urunler.etiketler'),
        ),
    ]
