# Generated by Django 5.2.6 on 2025-09-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0008_etiketler_urunler_etiketler'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiketler',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
