# Generated by Django 5.2.6 on 2025-09-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_etiketler_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='anasayfa',
            field=models.BooleanField(default=False),
        ),
    ]
